List<Map<String, String>> NotificationsData = [
  {
    'name': 'Shweta',
    'location': 'PDPU Crossroad, Kuasan (1.2km)',
    'rating': '4.5',
    'acceptin': '00h:30m',
    'pickupdatetime': '25 June | 04pm - 06pm',
    'deldatetime': '25 June | 04pm - 06pm',
    'notitype': 'Pickup Successfull',
    'notidate': 'Today at 8:09 am',
    'notitime': '05:05 PM',
    'ordernumber': '#445646586',
    'status': 'pickup',
  },
  {
    'name': 'John',
    'location': 'Main Street, City Center (0.8km)',
    'rating': '4.2',
    'acceptin': '00h:25m',
    'pickupdatetime': '26 June | 05pm - 07pm',
    'deldatetime': '26 June | 05pm - 07pm',
    'notidate': 'Yesterday at 8:09 am',
    'notitime': '05:05 PM',
    'notitype': 'Delivery Successfull',
    'ordernumber': '#445646586',
    'status': 'deliver'
  },
  {
    'name': 'Alice',
    'location': 'Park Avenue, Suburb (3.5km)',
    'rating': '4.7',
    'acceptin': '00h:35m',
    'pickupdatetime': '27 June | 03pm - 05pm',
    'deldatetime': '27 June | 03pm - 05pm',
    'notidate': 'Yesterday at 8:09 am',
    'notitime': '05:05 PM',
    'notitype': 'Delivery Successfull',
    'ordernumber': '#445646586',
    'status': 'deliver'
  },
  {
    'name': 'Michael',
    'location': 'Ocean Drive, Beachfront (5.0km)',
    'rating': '4.9',
    'acceptin': '00h:20m',
    'pickupdatetime': '28 June | 06pm - 08pm',
    'deldatetime': '28 June | 06pm - 08pm',
    'notidate': '26 June at 8:09 am',
    'notitime': '05:05 PM',
    'notitype': 'Pickup Successfull',
    'ordernumber': '#445646586',
    'status': 'pickup'
  },
];
